/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const YieldScenario = IDL.Variant({
  'conservative' : IDL.Null,
  'realistic' : IDL.Null,
  'optimistic' : IDL.Null,
});
export const EconomicsInput = IDL.Record({
  'seedCostUsd' : IDL.Float64,
  'landAreaHectares' : IDL.Float64,
  'pesticideCostUsd' : IDL.Float64,
  'cropId' : IDL.Text,
  'fertilizerCostUsd' : IDL.Float64,
  'irrigationCostUsd' : IDL.Float64,
  'scenario' : YieldScenario,
  'equipmentCostUsd' : IDL.Float64,
  'laborCostUsd' : IDL.Float64,
});
export const EconomicsResult = IDL.Record({
  'netProfitUsd' : IDL.Float64,
  'totalProductionCostUsd' : IDL.Float64,
  'grossRevenueUsd' : IDL.Float64,
  'marketPricePerKgUsd' : IDL.Float64,
  'breakEvenPricePerKgUsd' : IDL.Float64,
  'estimatedYieldKg' : IDL.Float64,
});
export const AnalysisId = IDL.Nat;
export const Timestamp = IDL.Int;
export const SoilType = IDL.Variant({
  'sandyLoam' : IDL.Null,
  'clay' : IDL.Null,
  'loam' : IDL.Null,
  'sand' : IDL.Null,
  'siltLoam' : IDL.Null,
});
export const ClimateZone = IDL.Variant({
  'temperate' : IDL.Null,
  'mediterranean' : IDL.Null,
  'continental' : IDL.Null,
  'arid' : IDL.Null,
  'semiarid' : IDL.Null,
  'tropical' : IDL.Null,
});
export const LandType = IDL.Variant({
  'hilly' : IDL.Null,
  'flat' : IDL.Null,
  'slope' : IDL.Null,
  'terraced' : IDL.Null,
});
export const SoilInput = IDL.Record({
  'soilType' : SoilType,
  'climateZone' : ClimateZone,
  'landType' : LandType,
  'waterAvailabilityMm' : IDL.Nat,
});
export const SavedAnalysis = IDL.Record({
  'id' : AnalysisId,
  'createdAt' : Timestamp,
  'topCropId' : IDL.Text,
  'topCropName' : IDL.Text,
  'input' : SoilInput,
  'topMatchScore' : IDL.Nat,
});
export const GrowingConditions = IDL.Record({
  'suitableClimates' : IDL.Vec(ClimateZone),
  'soilPhMax' : IDL.Float64,
  'soilPhMin' : IDL.Float64,
  'suitableSoils' : IDL.Vec(SoilType),
  'minTempCelsius' : IDL.Int,
  'maxRainfallMm' : IDL.Nat,
  'minRainfallMm' : IDL.Nat,
  'suitableLandTypes' : IDL.Vec(LandType),
  'maxTempCelsius' : IDL.Int,
});
export const CropInfo = IDL.Record({
  'id' : IDL.Text,
  'growingSeasonDays' : IDL.Nat,
  'name' : IDL.Text,
  'waterRequirementMm' : IDL.Nat,
  'description' : IDL.Text,
  'conditions' : GrowingConditions,
  'marketPricePerKg' : IDL.Float64,
  'typicalYieldKgPerHectare' : IDL.Nat,
});
export const CropRecommendation = IDL.Record({
  'suitabilityReason' : IDL.Text,
  'crop' : CropInfo,
  'matchScore' : IDL.Nat,
});

export const idlService = IDL.Service({
  'computeEconomics' : IDL.Func([EconomicsInput], [EconomicsResult], ['query']),
  'deleteAnalysis' : IDL.Func([AnalysisId], [IDL.Bool], []),
  'getAnalysis' : IDL.Func([AnalysisId], [IDL.Opt(SavedAnalysis)], ['query']),
  'getCropById' : IDL.Func([IDL.Text], [IDL.Opt(CropInfo)], ['query']),
  'getCropCatalog' : IDL.Func([], [IDL.Vec(CropInfo)], ['query']),
  'getRecommendations' : IDL.Func(
      [SoilInput],
      [IDL.Vec(CropRecommendation)],
      ['query'],
    ),
  'listAnalyses' : IDL.Func([], [IDL.Vec(SavedAnalysis)], ['query']),
  'saveAnalysis' : IDL.Func(
      [SoilInput, IDL.Text, IDL.Text, IDL.Nat],
      [SavedAnalysis],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const YieldScenario = IDL.Variant({
    'conservative' : IDL.Null,
    'realistic' : IDL.Null,
    'optimistic' : IDL.Null,
  });
  const EconomicsInput = IDL.Record({
    'seedCostUsd' : IDL.Float64,
    'landAreaHectares' : IDL.Float64,
    'pesticideCostUsd' : IDL.Float64,
    'cropId' : IDL.Text,
    'fertilizerCostUsd' : IDL.Float64,
    'irrigationCostUsd' : IDL.Float64,
    'scenario' : YieldScenario,
    'equipmentCostUsd' : IDL.Float64,
    'laborCostUsd' : IDL.Float64,
  });
  const EconomicsResult = IDL.Record({
    'netProfitUsd' : IDL.Float64,
    'totalProductionCostUsd' : IDL.Float64,
    'grossRevenueUsd' : IDL.Float64,
    'marketPricePerKgUsd' : IDL.Float64,
    'breakEvenPricePerKgUsd' : IDL.Float64,
    'estimatedYieldKg' : IDL.Float64,
  });
  const AnalysisId = IDL.Nat;
  const Timestamp = IDL.Int;
  const SoilType = IDL.Variant({
    'sandyLoam' : IDL.Null,
    'clay' : IDL.Null,
    'loam' : IDL.Null,
    'sand' : IDL.Null,
    'siltLoam' : IDL.Null,
  });
  const ClimateZone = IDL.Variant({
    'temperate' : IDL.Null,
    'mediterranean' : IDL.Null,
    'continental' : IDL.Null,
    'arid' : IDL.Null,
    'semiarid' : IDL.Null,
    'tropical' : IDL.Null,
  });
  const LandType = IDL.Variant({
    'hilly' : IDL.Null,
    'flat' : IDL.Null,
    'slope' : IDL.Null,
    'terraced' : IDL.Null,
  });
  const SoilInput = IDL.Record({
    'soilType' : SoilType,
    'climateZone' : ClimateZone,
    'landType' : LandType,
    'waterAvailabilityMm' : IDL.Nat,
  });
  const SavedAnalysis = IDL.Record({
    'id' : AnalysisId,
    'createdAt' : Timestamp,
    'topCropId' : IDL.Text,
    'topCropName' : IDL.Text,
    'input' : SoilInput,
    'topMatchScore' : IDL.Nat,
  });
  const GrowingConditions = IDL.Record({
    'suitableClimates' : IDL.Vec(ClimateZone),
    'soilPhMax' : IDL.Float64,
    'soilPhMin' : IDL.Float64,
    'suitableSoils' : IDL.Vec(SoilType),
    'minTempCelsius' : IDL.Int,
    'maxRainfallMm' : IDL.Nat,
    'minRainfallMm' : IDL.Nat,
    'suitableLandTypes' : IDL.Vec(LandType),
    'maxTempCelsius' : IDL.Int,
  });
  const CropInfo = IDL.Record({
    'id' : IDL.Text,
    'growingSeasonDays' : IDL.Nat,
    'name' : IDL.Text,
    'waterRequirementMm' : IDL.Nat,
    'description' : IDL.Text,
    'conditions' : GrowingConditions,
    'marketPricePerKg' : IDL.Float64,
    'typicalYieldKgPerHectare' : IDL.Nat,
  });
  const CropRecommendation = IDL.Record({
    'suitabilityReason' : IDL.Text,
    'crop' : CropInfo,
    'matchScore' : IDL.Nat,
  });
  
  return IDL.Service({
    'computeEconomics' : IDL.Func(
        [EconomicsInput],
        [EconomicsResult],
        ['query'],
      ),
    'deleteAnalysis' : IDL.Func([AnalysisId], [IDL.Bool], []),
    'getAnalysis' : IDL.Func([AnalysisId], [IDL.Opt(SavedAnalysis)], ['query']),
    'getCropById' : IDL.Func([IDL.Text], [IDL.Opt(CropInfo)], ['query']),
    'getCropCatalog' : IDL.Func([], [IDL.Vec(CropInfo)], ['query']),
    'getRecommendations' : IDL.Func(
        [SoilInput],
        [IDL.Vec(CropRecommendation)],
        ['query'],
      ),
    'listAnalyses' : IDL.Func([], [IDL.Vec(SavedAnalysis)], ['query']),
    'saveAnalysis' : IDL.Func(
        [SoilInput, IDL.Text, IDL.Text, IDL.Nat],
        [SavedAnalysis],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };