/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AnalysisId = bigint;
export type ClimateZone = { 'temperate' : null } |
  { 'mediterranean' : null } |
  { 'continental' : null } |
  { 'arid' : null } |
  { 'semiarid' : null } |
  { 'tropical' : null };
export interface CropInfo {
  'id' : string,
  'growingSeasonDays' : bigint,
  'name' : string,
  'waterRequirementMm' : bigint,
  'description' : string,
  'conditions' : GrowingConditions,
  'marketPricePerKg' : number,
  'typicalYieldKgPerHectare' : bigint,
}
export interface CropRecommendation {
  'suitabilityReason' : string,
  'crop' : CropInfo,
  'matchScore' : bigint,
}
export interface EconomicsInput {
  'seedCostUsd' : number,
  'landAreaHectares' : number,
  'pesticideCostUsd' : number,
  'cropId' : string,
  'fertilizerCostUsd' : number,
  'irrigationCostUsd' : number,
  'scenario' : YieldScenario,
  'equipmentCostUsd' : number,
  'laborCostUsd' : number,
}
export interface EconomicsResult {
  'netProfitUsd' : number,
  'totalProductionCostUsd' : number,
  'grossRevenueUsd' : number,
  'marketPricePerKgUsd' : number,
  'breakEvenPricePerKgUsd' : number,
  'estimatedYieldKg' : number,
}
export interface GrowingConditions {
  'suitableClimates' : Array<ClimateZone>,
  'soilPhMax' : number,
  'soilPhMin' : number,
  'suitableSoils' : Array<SoilType>,
  'minTempCelsius' : bigint,
  'maxRainfallMm' : bigint,
  'minRainfallMm' : bigint,
  'suitableLandTypes' : Array<LandType>,
  'maxTempCelsius' : bigint,
}
export type LandType = { 'hilly' : null } |
  { 'flat' : null } |
  { 'slope' : null } |
  { 'terraced' : null };
export interface SavedAnalysis {
  'id' : AnalysisId,
  'createdAt' : Timestamp,
  'topCropId' : string,
  'topCropName' : string,
  'input' : SoilInput,
  'topMatchScore' : bigint,
}
export interface SoilInput {
  'soilType' : SoilType,
  'climateZone' : ClimateZone,
  'landType' : LandType,
  'waterAvailabilityMm' : bigint,
}
export type SoilType = { 'sandyLoam' : null } |
  { 'clay' : null } |
  { 'loam' : null } |
  { 'sand' : null } |
  { 'siltLoam' : null };
export type Timestamp = bigint;
export type YieldScenario = { 'conservative' : null } |
  { 'realistic' : null } |
  { 'optimistic' : null };
export interface _SERVICE {
  'computeEconomics' : ActorMethod<[EconomicsInput], EconomicsResult>,
  'deleteAnalysis' : ActorMethod<[AnalysisId], boolean>,
  'getAnalysis' : ActorMethod<[AnalysisId], [] | [SavedAnalysis]>,
  'getCropById' : ActorMethod<[string], [] | [CropInfo]>,
  'getCropCatalog' : ActorMethod<[], Array<CropInfo>>,
  'getRecommendations' : ActorMethod<[SoilInput], Array<CropRecommendation>>,
  'listAnalyses' : ActorMethod<[], Array<SavedAnalysis>>,
  'saveAnalysis' : ActorMethod<
    [SoilInput, string, string, bigint],
    SavedAnalysis
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];