/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface SoilInput {
    soilType: SoilType;
    climateZone: ClimateZone;
    landType: LandType;
    waterAvailabilityMm: bigint;
}
export interface SavedAnalysis {
    id: AnalysisId;
    createdAt: Timestamp;
    topCropId: string;
    topCropName: string;
    input: SoilInput;
    topMatchScore: bigint;
}
export interface GrowingConditions {
    suitableClimates: Array<ClimateZone>;
    soilPhMax: number;
    soilPhMin: number;
    suitableSoils: Array<SoilType>;
    minTempCelsius: bigint;
    maxRainfallMm: bigint;
    minRainfallMm: bigint;
    suitableLandTypes: Array<LandType>;
    maxTempCelsius: bigint;
}
export interface CropInfo {
    id: string;
    growingSeasonDays: bigint;
    name: string;
    waterRequirementMm: bigint;
    description: string;
    conditions: GrowingConditions;
    marketPricePerKg: number;
    typicalYieldKgPerHectare: bigint;
}
export interface EconomicsResult {
    netProfitUsd: number;
    totalProductionCostUsd: number;
    grossRevenueUsd: number;
    marketPricePerKgUsd: number;
    breakEvenPricePerKgUsd: number;
    estimatedYieldKg: number;
}
export type AnalysisId = bigint;
export interface CropRecommendation {
    suitabilityReason: string;
    crop: CropInfo;
    matchScore: bigint;
}
export interface EconomicsInput {
    seedCostUsd: number;
    landAreaHectares: number;
    pesticideCostUsd: number;
    cropId: string;
    fertilizerCostUsd: number;
    irrigationCostUsd: number;
    scenario: YieldScenario;
    equipmentCostUsd: number;
    laborCostUsd: number;
}
export enum ClimateZone {
    temperate = "temperate",
    mediterranean = "mediterranean",
    continental = "continental",
    arid = "arid",
    semiarid = "semiarid",
    tropical = "tropical"
}
export enum LandType {
    hilly = "hilly",
    flat = "flat",
    slope = "slope",
    terraced = "terraced"
}
export enum SoilType {
    sandyLoam = "sandyLoam",
    clay = "clay",
    loam = "loam",
    sand = "sand",
    siltLoam = "siltLoam"
}
export enum YieldScenario {
    conservative = "conservative",
    realistic = "realistic",
    optimistic = "optimistic"
}
export interface backendInterface {
    computeEconomics(econ: EconomicsInput): Promise<EconomicsResult>;
    deleteAnalysis(id: AnalysisId): Promise<boolean>;
    getAnalysis(id: AnalysisId): Promise<SavedAnalysis | null>;
    getCropById(cropId: string): Promise<CropInfo | null>;
    getCropCatalog(): Promise<Array<CropInfo>>;
    getRecommendations(input: SoilInput): Promise<Array<CropRecommendation>>;
    listAnalyses(): Promise<Array<SavedAnalysis>>;
    saveAnalysis(input: SoilInput, topCropId: string, topCropName: string, topMatchScore: bigint): Promise<SavedAnalysis>;
}
import type { AnalysisId as _AnalysisId, ClimateZone as _ClimateZone, CropInfo as _CropInfo, CropRecommendation as _CropRecommendation, EconomicsInput as _EconomicsInput, GrowingConditions as _GrowingConditions, LandType as _LandType, SavedAnalysis as _SavedAnalysis, SoilInput as _SoilInput, SoilType as _SoilType, Timestamp as _Timestamp, YieldScenario as _YieldScenario } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async computeEconomics(arg0: EconomicsInput): Promise<EconomicsResult> {
        if (this.processError) {
            try {
                const result = await this.actor.computeEconomics(to_candid_EconomicsInput_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.computeEconomics(to_candid_EconomicsInput_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteAnalysis(arg0: AnalysisId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnalysis(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnalysis(arg0);
            return result;
        }
    }
    async getAnalysis(arg0: AnalysisId): Promise<SavedAnalysis | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalysis(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalysis(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCropById(arg0: string): Promise<CropInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCropById(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCropById(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCropCatalog(): Promise<Array<CropInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCropCatalog();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCropCatalog();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecommendations(arg0: SoilInput): Promise<Array<CropRecommendation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendations(to_candid_SoilInput_n25(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendations(to_candid_SoilInput_n25(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAnalyses(): Promise<Array<SavedAnalysis>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAnalyses();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAnalyses();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveAnalysis(arg0: SoilInput, arg1: string, arg2: string, arg3: bigint): Promise<SavedAnalysis> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAnalysis(to_candid_SoilInput_n25(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
                return from_candid_SavedAnalysis_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAnalysis(to_candid_SoilInput_n25(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
            return from_candid_SavedAnalysis_n6(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ClimateZone_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClimateZone): ClimateZone {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_CropInfo_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CropInfo): CropInfo {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_CropRecommendation_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CropRecommendation): CropRecommendation {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_GrowingConditions_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GrowingConditions): GrowingConditions {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_LandType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LandType): LandType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_SavedAnalysis_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SavedAnalysis): SavedAnalysis {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_SoilInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SoilInput): SoilInput {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_SoilType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SoilType): SoilType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CropInfo]): CropInfo | null {
    return value.length === 0 ? null : from_candid_CropInfo_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SavedAnalysis]): SavedAnalysis | null {
    return value.length === 0 ? null : from_candid_SavedAnalysis_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    growingSeasonDays: bigint;
    name: string;
    waterRequirementMm: bigint;
    description: string;
    conditions: _GrowingConditions;
    marketPricePerKg: number;
    typicalYieldKgPerHectare: bigint;
}): {
    id: string;
    growingSeasonDays: bigint;
    name: string;
    waterRequirementMm: bigint;
    description: string;
    conditions: GrowingConditions;
    marketPricePerKg: number;
    typicalYieldKgPerHectare: bigint;
} {
    return {
        id: value.id,
        growingSeasonDays: value.growingSeasonDays,
        name: value.name,
        waterRequirementMm: value.waterRequirementMm,
        description: value.description,
        conditions: from_candid_GrowingConditions_n19(_uploadFile, _downloadFile, value.conditions),
        marketPricePerKg: value.marketPricePerKg,
        typicalYieldKgPerHectare: value.typicalYieldKgPerHectare
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    suitableClimates: Array<_ClimateZone>;
    soilPhMax: number;
    soilPhMin: number;
    suitableSoils: Array<_SoilType>;
    minTempCelsius: bigint;
    maxRainfallMm: bigint;
    minRainfallMm: bigint;
    suitableLandTypes: Array<_LandType>;
    maxTempCelsius: bigint;
}): {
    suitableClimates: Array<ClimateZone>;
    soilPhMax: number;
    soilPhMin: number;
    suitableSoils: Array<SoilType>;
    minTempCelsius: bigint;
    maxRainfallMm: bigint;
    minRainfallMm: bigint;
    suitableLandTypes: Array<LandType>;
    maxTempCelsius: bigint;
} {
    return {
        suitableClimates: from_candid_vec_n21(_uploadFile, _downloadFile, value.suitableClimates),
        soilPhMax: value.soilPhMax,
        soilPhMin: value.soilPhMin,
        suitableSoils: from_candid_vec_n22(_uploadFile, _downloadFile, value.suitableSoils),
        minTempCelsius: value.minTempCelsius,
        maxRainfallMm: value.maxRainfallMm,
        minRainfallMm: value.minRainfallMm,
        suitableLandTypes: from_candid_vec_n23(_uploadFile, _downloadFile, value.suitableLandTypes),
        maxTempCelsius: value.maxTempCelsius
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    suitabilityReason: string;
    crop: _CropInfo;
    matchScore: bigint;
}): {
    suitabilityReason: string;
    crop: CropInfo;
    matchScore: bigint;
} {
    return {
        suitabilityReason: value.suitabilityReason,
        crop: from_candid_CropInfo_n17(_uploadFile, _downloadFile, value.crop),
        matchScore: value.matchScore
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AnalysisId;
    createdAt: _Timestamp;
    topCropId: string;
    topCropName: string;
    input: _SoilInput;
    topMatchScore: bigint;
}): {
    id: AnalysisId;
    createdAt: Timestamp;
    topCropId: string;
    topCropName: string;
    input: SoilInput;
    topMatchScore: bigint;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        topCropId: value.topCropId,
        topCropName: value.topCropName,
        input: from_candid_SoilInput_n8(_uploadFile, _downloadFile, value.input),
        topMatchScore: value.topMatchScore
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    soilType: _SoilType;
    climateZone: _ClimateZone;
    landType: _LandType;
    waterAvailabilityMm: bigint;
}): {
    soilType: SoilType;
    climateZone: ClimateZone;
    landType: LandType;
    waterAvailabilityMm: bigint;
} {
    return {
        soilType: from_candid_SoilType_n10(_uploadFile, _downloadFile, value.soilType),
        climateZone: from_candid_ClimateZone_n12(_uploadFile, _downloadFile, value.climateZone),
        landType: from_candid_LandType_n14(_uploadFile, _downloadFile, value.landType),
        waterAvailabilityMm: value.waterAvailabilityMm
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sandyLoam: null;
} | {
    clay: null;
} | {
    loam: null;
} | {
    sand: null;
} | {
    siltLoam: null;
}): SoilType {
    return "sandyLoam" in value ? SoilType.sandyLoam : "clay" in value ? SoilType.clay : "loam" in value ? SoilType.loam : "sand" in value ? SoilType.sand : "siltLoam" in value ? SoilType.siltLoam : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    temperate: null;
} | {
    mediterranean: null;
} | {
    continental: null;
} | {
    arid: null;
} | {
    semiarid: null;
} | {
    tropical: null;
}): ClimateZone {
    return "temperate" in value ? ClimateZone.temperate : "mediterranean" in value ? ClimateZone.mediterranean : "continental" in value ? ClimateZone.continental : "arid" in value ? ClimateZone.arid : "semiarid" in value ? ClimateZone.semiarid : "tropical" in value ? ClimateZone.tropical : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hilly: null;
} | {
    flat: null;
} | {
    slope: null;
} | {
    terraced: null;
}): LandType {
    return "hilly" in value ? LandType.hilly : "flat" in value ? LandType.flat : "slope" in value ? LandType.slope : "terraced" in value ? LandType.terraced : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClimateZone>): Array<ClimateZone> {
    return value.map((x)=>from_candid_ClimateZone_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SoilType>): Array<SoilType> {
    return value.map((x)=>from_candid_SoilType_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LandType>): Array<LandType> {
    return value.map((x)=>from_candid_LandType_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CropInfo>): Array<CropInfo> {
    return value.map((x)=>from_candid_CropInfo_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CropRecommendation>): Array<CropRecommendation> {
    return value.map((x)=>from_candid_CropRecommendation_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SavedAnalysis>): Array<SavedAnalysis> {
    return value.map((x)=>from_candid_SavedAnalysis_n6(_uploadFile, _downloadFile, x));
}
function to_candid_ClimateZone_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClimateZone): _ClimateZone {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_EconomicsInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EconomicsInput): _EconomicsInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_LandType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LandType): _LandType {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_SoilInput_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SoilInput): _SoilInput {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_SoilType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SoilType): _SoilType {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_YieldScenario_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: YieldScenario): _YieldScenario {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    seedCostUsd: number;
    landAreaHectares: number;
    pesticideCostUsd: number;
    cropId: string;
    fertilizerCostUsd: number;
    irrigationCostUsd: number;
    scenario: YieldScenario;
    equipmentCostUsd: number;
    laborCostUsd: number;
}): {
    seedCostUsd: number;
    landAreaHectares: number;
    pesticideCostUsd: number;
    cropId: string;
    fertilizerCostUsd: number;
    irrigationCostUsd: number;
    scenario: _YieldScenario;
    equipmentCostUsd: number;
    laborCostUsd: number;
} {
    return {
        seedCostUsd: value.seedCostUsd,
        landAreaHectares: value.landAreaHectares,
        pesticideCostUsd: value.pesticideCostUsd,
        cropId: value.cropId,
        fertilizerCostUsd: value.fertilizerCostUsd,
        irrigationCostUsd: value.irrigationCostUsd,
        scenario: to_candid_YieldScenario_n3(_uploadFile, _downloadFile, value.scenario),
        equipmentCostUsd: value.equipmentCostUsd,
        laborCostUsd: value.laborCostUsd
    };
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    soilType: SoilType;
    climateZone: ClimateZone;
    landType: LandType;
    waterAvailabilityMm: bigint;
}): {
    soilType: _SoilType;
    climateZone: _ClimateZone;
    landType: _LandType;
    waterAvailabilityMm: bigint;
} {
    return {
        soilType: to_candid_SoilType_n27(_uploadFile, _downloadFile, value.soilType),
        climateZone: to_candid_ClimateZone_n29(_uploadFile, _downloadFile, value.climateZone),
        landType: to_candid_LandType_n31(_uploadFile, _downloadFile, value.landType),
        waterAvailabilityMm: value.waterAvailabilityMm
    };
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SoilType): {
    sandyLoam: null;
} | {
    clay: null;
} | {
    loam: null;
} | {
    sand: null;
} | {
    siltLoam: null;
} {
    return value == SoilType.sandyLoam ? {
        sandyLoam: null
    } : value == SoilType.clay ? {
        clay: null
    } : value == SoilType.loam ? {
        loam: null
    } : value == SoilType.sand ? {
        sand: null
    } : value == SoilType.siltLoam ? {
        siltLoam: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClimateZone): {
    temperate: null;
} | {
    mediterranean: null;
} | {
    continental: null;
} | {
    arid: null;
} | {
    semiarid: null;
} | {
    tropical: null;
} {
    return value == ClimateZone.temperate ? {
        temperate: null
    } : value == ClimateZone.mediterranean ? {
        mediterranean: null
    } : value == ClimateZone.continental ? {
        continental: null
    } : value == ClimateZone.arid ? {
        arid: null
    } : value == ClimateZone.semiarid ? {
        semiarid: null
    } : value == ClimateZone.tropical ? {
        tropical: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LandType): {
    hilly: null;
} | {
    flat: null;
} | {
    slope: null;
} | {
    terraced: null;
} {
    return value == LandType.hilly ? {
        hilly: null
    } : value == LandType.flat ? {
        flat: null
    } : value == LandType.slope ? {
        slope: null
    } : value == LandType.terraced ? {
        terraced: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: YieldScenario): {
    conservative: null;
} | {
    realistic: null;
} | {
    optimistic: null;
} {
    return value == YieldScenario.conservative ? {
        conservative: null
    } : value == YieldScenario.realistic ? {
        realistic: null
    } : value == YieldScenario.optimistic ? {
        optimistic: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
